### ISSUE TITLE
Need little help

### ISSUE THREAD

**Issue by dev-drprasad** [iromise/AOS-Note#1]
Hi,

Sorry to contact you like this. You seems to have expertise on archive files and I need small help.

I have a file which looks similar to zip file (I am not sure though, I actually renamed file to .zip so that github allow me to upload).
I inspected its header and pattern looks similar to zip. But I tried to open it with zip unarchiver (7zip, WinRaR etc) but I get invalid error. Can you help me to understand what is this file exactly ? If its zip kind of file, can I extract it ?

Thank you!

[Adventure Island4 - Copy.zip](https://github.com/iromise/AOS-Note/files/5760159/Adventure.Island4.-.Copy.zip)

**Comment by iromise** [comment]
I am not sure how you find me, but how do you think that I have expertise on archive files?

**Comment by dev-drprasad** [comment]
I saw an article about decrypting zip files in https://ctf-wiki.github.io/ctf-wiki/. 
Anyway don't bother.

Thanks for reply
